typography_spectrum: 0.3200985847506672
color:
  brandStrength: 0.3249372960999608
  lightness: 0.6825762970838696
  saturation: 0.8519399296492338
  rhythmicContrast: 0.4624462847132236
  brandColors:
    - '#F9E4AD'
    - '#E6B098'
    - '#CC4452'
    - '#723147'
    - '#31152B'
layout_spectrum: 0.7898570084944367
name: Castle Purchasing
navigation:
  - name: Profit Enhancing Specialists
    url: 'http://www.castlepurchasing.co.uk'
    type: external
description: The Profit Enhancing Specialists
